References updated. Added links and fixed formatting (#1105)
Qiskit/platypus pull request #1109
Opened 2022-06-07 03:29 UTC by MarcoBarroca

## Changes
I had to redo PR #1107  #because git wasn't properly configured with my GitHub e-mail and I couldn't sign the CLA. Fixes the References section formatting mismatch in the Unsupervised learning notebook and adds a missing link in the Quantum Feature maps notebook in the Machine Learning Chapter. Issues #716 and #1105 

## Implementation details
Corrected the formatting of the references in the mentioned Notebooks

## How to read this PR
Check the differences in the reference section in the mentioned notebooks.

## Screenshots
Quantum feature maps notebook:
<img width="993" alt="Screen Shot 2022-06-06 at 16 14 26" src="https://user-images.githubusercontent.com/6553024/172289537-8f1a99c6-5ddf-4b09-9346-5b56c8439484.png">

Unsupervised Learning Notebook:
<img width="986" alt="Screen Shot 2022-06-06 at 16 12 28" src="https://user-images.githubusercontent.com/6553024/172289576-92a2d5a9-467b-4f02-8dcd-e6c6e04ae310.png">

2022-06-13 09:55 UTC, Tansito requested changes

2022-06-13 09:55 UTC, Tansito commented on notebooks/quantum-machine-learning/kernel.ipynb
> +   "display_name": "Python 3 (ipykernel)",
Thanks for your PR @MarcoBarroca ! Could you remove these changes that are not related with the content? 🙏

2022-06-13 09:55 UTC, Tansito commented on notebooks/quantum-machine-learning/kernel.ipynb
> +   "version": "3.10.4"
Same for this change.

2022-06-13 09:55 UTC, Tansito commented on notebooks/quantum-machine-learning/unsupervised.ipynb
> +   "display_name": "Python 3 (ipykernel)",
Same as the changes from my previous reviews.

2022-06-13 09:55 UTC, Tansito commented on notebooks/quantum-machine-learning/unsupervised.ipynb
> +   "version": "3.10.4"
The last one change to be removed!

2022-06-13 10:42 UTC, MarcoBarroca commented on notebooks/quantum-machine-learning/unsupervised.ipynb
> +   "version": "3.10.4"
I just removed those changes!

2022-06-14 09:40 UTC, frankharkins submitted a review, later dismissed
Awesome, thank you!

2022-06-20 12:40 UTC, MarcoBarroca commented
Hey @Tansito the change request still seems to be blocking the merge despite being resolved.

2022-06-21 10:25 UTC, Tansito commented
Thanks @MarcoBarroca , I asked again to @frankharkins again for the review.

2022-06-23 10:00 UTC, Tansito approved these changes

2022-06-23 10:00 UTC, merged