Add scratchpad to side panel
Qiskit/platypus pull request #1150
Opened 2022-06-14 18:44 UTC by techtolentino

## Changes

Closes #1059 

## Implementation details

- added `CodeEditor`, `ExerciseActionsBar`, and `CodeOutput` to sidepanel
- added `run()` functionality (based off `CodeExercise` implemenation)

## Screenshots

https://user-images.githubusercontent.com/6276074/173665204-0e3a065f-b519-4122-8929-4b8f84eaa7e0.mov

2022-06-15 14:37 UTC, Tansito commented
I missed this question in the corresponding PR but now that I'm taking a look to all the courses with the integration for me it seems a bit weird having the `Run` button in a different position depending of the `CodeCell`. I assume it's intended but I would like to know the reason:

<img width="1043" alt="Screenshot 2022-06-15 at 16 34 52" src="https://user-images.githubusercontent.com/9059044/173854316-f623ed32-6e62-4f2e-8861-bff5362aafa9.png">

2022-06-15 15:24 UTC, korgan00 requested changes
Code LGTM, I just have a minor change.
Regarding design, the design puts the button over the code cell

Current implementation:
![Captura de Pantalla 2022-06-15 a las 17 11 13](https://user-images.githubusercontent.com/4138279/173863809-cdf4d87c-6758-4ff4-9dfa-7bbd9da8454b.png)
Figma:
![Captura de Pantalla 2022-06-15 a las 17 11 24](https://user-images.githubusercontent.com/4138279/173863819-9463c824-4318-43e2-b9c3-fac9914caed4.png)

Also, Figma has an initial code comment.

2022-06-15 16:31 UTC, techtolentino commented
@Tansito @korgan00 -- thanks for the feedback. 

I've updated the PR and the video capture, to show that the run button is now positioned _within_ the `CodeEditor` as expected.

2022-06-16 12:05 UTC, korgan00 approved these changes

2022-06-16 12:06 UTC, merged