Aligned the reset button to the reset text
Qiskit/platypus pull request #1496
Opened 2022-08-30 11:41 UTC by mariacloehb

## Changes

## Implementation details

## How to read this PR

## Screenshots

2022-08-30 11:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/platypus?pullRequest=1496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/platypus?pullRequest=1496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/platypus?pullRequest=1496) it.</sub>

2022-08-30 13:29 UTC, eddybrando requested changes
Thanks a lot for your first PR @mariacloehb! 🙂

I added a couple of comments.

We need to get rid of changes that are not relevant to the PR. I added comments on those.

I liked the renaming of the icon component. It's a good practice to fix this kind of stuff as we see it.

To solve the alignment issue, there is a simpler approach: We can just add `align-items: center` to the `mini-composer__circuit-section__reset` CSS class. That way, we. don't need to make the height and width adjustments.

I strongly recommend this resource to leverage the power of flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2022-08-30 13:29 UTC, eddybrando commented on frontend/scss/vendor/mathigon.scss
> +
I believe this wasn't meant to be included:

```suggestion
```

2022-08-30 13:29 UTC, eddybrando commented on frontend/scss/vendor/mathigon.scss
> +
I believe this wasn't meant to be included:

```suggestion
```

2022-08-30 13:29 UTC, eddybrando commented on frontend/vue/components/MiniComposer/CircuitSandboxWidget.vue
> +        </h1>rm
I believe this wasn't meant to be included:

```suggestion
        </h1>
```

2022-08-30 13:29 UTC, eddybrando commented on frontend/vue/components/MiniComposer/CircuitSandboxWidget.vue
> +      Reset <ResetIcon class="mini-composer__circuit-section__reset__icon" />
Here we need to remove the empty line and add some indentation:

```suggestion
        Reset <ResetIcon class="mini-composer__circuit-section__reset__icon" />
```

2022-08-30 13:29 UTC, eddybrando commented on frontend/vue/components/MiniComposer/CircuitSandboxWidget.vue
> +import ResetIcon from '@carbon/icons-vue/lib/reset/16'
Nice catch 👍

2022-09-15 12:45 UTC, eddybrando commented on frontend/scss/vendor/mathigon.scss
> +
```suggestion
```

2022-09-21 22:57 UTC, techtolentino requested changes
The reset alignment looks great, nicely done 👏🏼 

Just leaving a comment about whether or not the `mini-composer__state-views__area` height and width needed updating.

Thank you!

2022-09-21 22:57 UTC, techtolentino commented on frontend/vue/components/MiniComposer/CircuitSandboxWidget.vue
> +      height: 16px;
One question I had here — I'm wondering if these values needed to change?

Updating the `height` and `width` caused the formula area to be too small. However, if we leave them at `height: 9rem` and `width: 100%`, the formula is readable.

Please see this screen capture in Firefox 👇🏼 



https://user-images.githubusercontent.com/6276074/191624451-5f3a5e2e-609b-4185-a04e-fdd8ee2c1750.mov

2022-10-10 17:00 UTC, techtolentino commented on frontend/vue/components/MiniComposer/CircuitSandboxWidget.vue
> +      height: 9rem;
@mariacloehb - this should just be 1rem... 

16px = 1rem

2022-10-10 17:28 UTC, techtolentino commented on frontend/vue/components/MiniComposer/CircuitSandboxWidget.vue
> +      height: 9rem;
wait, disregard...

2022-10-10 18:00 UTC, techtolentino approved these changes
Nicely done 👏🏼 

LGTM

2022-10-11 02:35 UTC, vabarbosa approved these changes
thank you!!

2022-10-11 02:36 UTC, merged