Introduction problem set
Qiskit/platypus pull request #1537
Opened 2022-09-08 13:33 UTC by amirhassank

## Changes

Added 3 new introductory problem sets

2022-09-08 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/platypus?pullRequest=1537) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/platypus?pullRequest=1537) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: vabarbosa<br/>:white_check_mark: daiki0623<br/>:white_check_mark: kifumi<br/>:white_check_mark: ryota-katsube<br/>:white_check_mark: KaoriNamba<br/>:white_check_mark: derwind<br/>:white_check_mark: ianhellstrom<br/>:white_check_mark: frankharkins<br/>:white_check_mark: ohken322<br/>:x: amirhassank<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/platypus?pullRequest=1537) it.</sub>

2022-09-08 14:33 UTC, pandasa123 commented
Hey @amirhassank, could you combine these into a single `quantum_states_and_operations.ipynb` file? @vabarbosa has created a smart way to have related problems living in one file while still having completions tracked. If we want different pages, use `##` instead

2022-09-09 16:51 UTC, vabarbosa requested changes
@amirhassank along with previous comments, you should also update the `goal` values. they should be unique

2022-09-09 16:51 UTC, vabarbosa commented on notebooks/problem-sets/Quantum states and operations/01.Single_qubit_quantum_states.ipynb
> +    "<!-- ::: q-quiz(goal=\"test-problem\") -->\n",
@amirhassank the `goal` should be a unique value. it appears you are using `test-problem` multiple times

2022-09-09 16:51 UTC, vabarbosa commented on notebooks/problem-sets/Quantum states and operations/02.Single_qubit_quantum_gate.ipynb
> +    "<!-- ::: q-quiz(goal=\"test-problem\") -->\n",
the `goal` should be a unique value. it appears you are using `test-problem` multiple times

2022-09-18 14:58 UTC, pandasa123 commented
@amirhassank, I believe the original folder needs to be deleted

2022-09-30 14:49 UTC, frankharkins requested changes
Thanks, I've made a couple of suggestions but otherwise everything looks good. You've still got some conflicting goal names (`quantum-states-and-operators-4`) which you'll need to change to pass the checks.

2022-09-30 14:49 UTC, frankharkins commented on notebooks/problem-sets/quantum_states_and_operations.ipynb
> +    "Which of the following operator is Hermitian?\n",
```suggestion
    "Which of the following operators is Hermitian?\n",
```

2022-10-10 18:48 UTC, pandasa123 commented
@amirhassank, is this ready to be reviewed?

2022-10-11 08:23 UTC, eddybrando commented
Hi @amirhassank, we'd need you to please sign the CLA: https://github.com/Qiskit/platypus/pull/1537#issuecomment-1240725637 🙂

2024-02-08 04:23 UTC, closed without merging