User account
Qiskit/platypus pull request #174
Opened 2021-10-18 12:47 UTC by eddybrando

related: https://github.com/Qiskit/platypus/issues/258

preview: https://platypus-pr-174.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/signin

2021-11-02 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/platypus?pullRequest=174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/platypus?pullRequest=174) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: techtolentino<br/>:x: eddybrando<br/>:x: vabarbosa<br/>:x: korgan00<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/platypus?pullRequest=174) it.</sub>

2021-11-02 22:54 UTC, vabarbosa commented
@JRussellHuffman here is the feature branch for the user acct updates.
the preview URL: https://platypus-pr-174.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/account

2021-11-03 14:23 UTC, JRussellHuffman commented
Wonderful, thank you! Do these links expire?

2021-11-03 14:26 UTC, vabarbosa commented
> Wonderful, thank you! Do these links expire?

not until the PR is closed

2021-11-03 15:41 UTC, JRussellHuffman commented
Good to know. 
More specifically, I'm thinking about doing some user testing and showing the user account page to some users just to validate the work so far. Ideally we use live code (ie that URL) instead of a clickable prototype. Any reason I shouldn't use that preview URL?

2021-11-03 15:45 UTC, vabarbosa commented
> Good to know. More specifically, I'm thinking about doing some user testing and showing the user account page to some users just to validate the work so far. Ideally we use live code (ie that URL) instead of a clickable prototype. Any reason I shouldn't use that preview URL?

no reason at all, unless it is missing something you need (or including something you dont want) in the user testing

2022-01-14 21:21 UTC, vabarbosa commented
draft PR can now be previewed so removing the `[WIP]` and putting into `Draft` so not to merge before ready

2022-02-23 21:14 UTC, techtolentino requested changes
Just a few simple comments from me... 👏🏽

2022-02-23 21:14 UTC, techtolentino commented on frontend/vue/components/SignIn/SignIn.vue
> +      <div class="sign-in__content-section sign-in__content-section__hero">
I think we could remove `-section` from this class...  and stick w/ `sign-in__content__hero`, and in the next line `sign-in__content__hero-title`

2022-02-23 21:14 UTC, techtolentino commented on frontend/vue/components/UserAccount/CourseProgress.vue
> +      class="course-progress__section-list"
I don't see this class being used, maybe we could remove it?

2022-02-23 21:14 UTC, techtolentino commented on frontend/vue/components/UserAccount/CourseProgress.vue
> +          class="course-progress__section"
I also don't see this class being used, maybe we could remove it?

2022-02-23 21:14 UTC, techtolentino commented on frontend/vue/components/UserAccount/PrivacySection.vue
> +      IBM Privacy Statement
we should add translation here and define the string in `strings.yaml`

2022-02-23 21:14 UTC, techtolentino commented on frontend/vue/components/UserAccount/PrivacySection.vue
> +      Privacy
this is defined in `strings.yaml`, we can use 

`{{ $translate('Privacy') }}`

2022-02-23 21:14 UTC, techtolentino commented on frontend/vue/components/UserAccount/PrivacySection.vue
> +      IBM Quantum End User Agreement
same comment, we should add translation here and define the string in `strings.yaml`

2022-02-25 18:14 UTC, techtolentino approved these changes

2022-02-28 07:37 UTC, Tansito approved these changes

2022-02-28 14:45 UTC, merged