vqe code update - primitives, qiskit-nature upgrade (0.5.2)
Qiskit/platypus pull request #1988
Opened 2023-03-07 17:31 UTC by david-alber

## Changes

Updates the vqe-molecule.ipynb example with the primitives Sampler and Estimator from qiskit_aer. 
The QubitConvertor/ParityMapper from qiskit_nature.second_q (latest advancements) are used.
The update required to upgrade qiskit-nature to 0.5.2.

Closes #1840

2023-03-08 16:33 UTC, david-alber commented
Pylint PR issues of trailing whitespaces and qiskit.primitives.are import are resolved with commit fb5deb54cf0b759a46eaec431014b363de6bff11

2023-03-10 12:32 UTC, frankharkins requested changes
Great work, thank you! I just have a couple of small comments.

2023-03-13 16:46 UTC, david-alber commented on notebooks/ch-applications/vqe-molecules.ipynb
> -    "                    measurement_error_mitigation_cls=qiskit.utils.mitigation.CompleteMeasFitter)"
Tackling error mitigation via the `resilinece_level` option is (as for now) not possiblie with the AerSimulator, see [here](https://github.com/Qiskit/qiskit-aer/issues/1658).
However, [IBM Runtime qasm simulator] (https://qiskit.org/documentation/partners/qiskit_ibm_runtime/how_to/noisy_simulators.html#set-the-backend-and-options-to-use) could be used. This requires to use the qiskit-ibm-runtime module.

2023-03-13 16:46 UTC, david-alber commented on notebooks/ch-applications/vqe-molecules.ipynb
> -    "                    measurement_error_mitigation_cls=qiskit.utils.mitigation.CompleteMeasFitter)"
I will add a note at the end of the notebook ;)

2023-03-13 19:51 UTC, frankharkins approved these changes
Looks good! Thanks again.

2023-03-13 19:51 UTC, frankharkins commented on notebooks/ch-applications/vqe-molecules.ipynb
> +    "When using an actual quantum device, or a true simulator such as the `AerSimulator` with `VQE(estimator, var_form, optimizer)` the calculation of the expectation value is as follows: A Hamiltoni
```suggestion
    "When using an actual quantum device, or a true simulator such as the `AerSimulator` with `VQE(estimator, var_form, optimizer)` the calculation of the expectation value is as follows: A Hamiltonian is represented as a sum of a Pauli strings, with each Pauli term acting on a qubit as specified by the mapping being used. Each Pauli string has a corresponding circuit appended to the circuit corresponding to $|\\psi(\\theta)\\rangle$. Subsequently, each of these circuits is executed, and all of the results are used to determine the expectation value of $H$ on $|\\psi(\\theta)\\rangle$. \n",
```

2023-03-13 21:39 UTC, merged