Quantum Enigma 005
Qiskit/platypus pull request #2055
Opened 2023-04-06 15:08 UTC by pandasa123

## Changes

## Implementation details

## How to read this PR

## Screenshots

2023-05-03 21:49 UTC, GhislainLefebvre requested changes

2023-05-03 21:49 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_005.ipynb
> +{
I'm not sure I should put this here, but it seems that the Problem Set on Enigma 001 currently on line is an old version (wider logo, old evaluation page, no link to Problem Set 002...) 

https://learn.qiskit.org/problem-sets/quantum_enigma_problem_set/overview

2023-05-03 21:49 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_005.ipynb
> +    "    The circuit can be simplified until only three gates remain in the algorithm.\n",
should read: "...until only two gates..."

2023-05-03 21:49 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_005.ipynb
> +    "1. Qubit 2 determines which vandal is involved: 0 is Constantin, 1 is Equilibria\n",
Add the following before Qubit 2

Qubit 0 is the park: O is Ozis and 1 is Ida
Qubit 1 is the colour: 0 is orange and 1 in indigo

2023-06-13 14:09 UTC, pandasa123 commented
Hey @GhislainLefebvre, looking into this today!

2023-06-18 15:30 UTC, pandasa123 commented on notebooks/problem-sets/quantum_enigma_005.ipynb
> +    "\n",
Added

2023-06-18 15:30 UTC, pandasa123 commented on notebooks/problem-sets/quantum_enigma_005.ipynb
> +{
Fixed!

2023-06-21 14:51 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    " \n",
Add:
problem_qc.measure(0,0)
problem_qc.measure(2,2)
so that we can run the code in the next box

2023-06-21 14:51 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "1. Qubit 0 is the park: O is Ozis and 1 is Ida\n",
0 instead of O in : 0 is Ozis

2023-06-21 14:51 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "result = backend.run(transpile(qc, backend), shots=1000).result()\n",
Replace qc by problem_qc

2023-06-21 14:51 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "counts  = result.get_counts(qc)\n",
Replace qc by problem_qc

2023-06-27 13:56 UTC, pandasa123 commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "problem_qc.draw(output='mpl')"
@GhislainLefebvre, do we have a collect state vector here?

2023-06-27 13:58 UTC, pandasa123 commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "problem_qc.draw(output='mpl')"
Actually, we use an `Operator` behind the scenes, so order (and phase) shouldn't matter here thankfully

2023-06-27 15:43 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "problem_qc.draw(output='mpl')"
Ok, it works! My bad

2023-06-27 15:43 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "problem_qc.draw(output='mpl')"
All good

2023-06-27 15:43 UTC, GhislainLefebvre commented on notebooks/problem-sets/quantum_enigma_deutsch.ipynb
> +    "problem_qc.measure(0,0)\n",
Add two spaces so that students know where to code.

2024-02-08 04:23 UTC, closed without merging