Algorithm Design Updates
Qiskit/platypus pull request #2081
Opened 2023-04-20 19:48 UTC by pandasa123

## Changes

We had excellent feedback from @ElePT, @mrossinek, @Cryoris on elements of the course + code implementation details

## Implementation details

## How to read this PR

## Screenshots

2023-04-20 19:54 UTC, mrossinek commented on notebooks/algorithm-design/ansatz/ansatz.ipynb
The other thing that I had mentioned was that I do not think it is really necessary to run the full driver here.
Since you are really only accessing the `num_spatial_orbitals` (which is an `int`) and `num_particles` (which is a `tuple[int, int]`), I think it would look "less scary" if you simply say something along the lines of:

> Assume we have a problem with 2 spatial orbitals and 2 electrons (1 alpha spin, 1 beta spin). To construct an ansatz for this problem, we can do this as follows....

And then simply do:
```python
num_spatial_orbitals = 2
num_particles = (1, 1)
```
and maybe put a comment as well as link to `ElectronicStructureProblem.num_spatial_orbitals` and `num_particles`, respectively somewhere

2023-04-20 19:54 UTC, mrossinek commented on notebooks/algorithm-design/ansatz/ansatz.ipynb
The same holds for the other 2 cases where you use Qiskit Nature

2023-04-20 21:01 UTC, ElePT reviewed
LGTM! Thanks for your fast reply to our feedback.

2023-04-21 10:44 UTC, frankharkins requested changes
It looks like at least some of this code doesn't work, but I also can't test "applications", "optimization", or "instances" as they take too long to run. Can you re-run these notebooks to check they work?

2023-04-21 10:44 UTC, frankharkins commented on notebooks/algorithm-design/cost_function/cost_function.ipynb
This notebook fails on cell 3

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 33
     29     return values
     32 theta_list = (2 * np.pi * np.random.rand(1, 8)).tolist()
---> 33 cost_function_vqe(theta_list)

Cell In[3], line 25, in cost_function_vqe(theta)
     22 backend = service.backend("ibmq_qasm_simulator")
     24 # Use estimator to get the expected values corresponding to each ansatz
---> 25 estimator = Estimator(session=backend)
     26 job = estimator.run(ansatz, observable, theta)
     27 values = job.result().values

TypeError: __init__() got an unexpected keyword argument 'session'
```

2023-04-21 13:32 UTC, ElePT commented on notebooks/algorithm-design/cost_function/cost_function.ipynb
🤔 what `qiskit-ibm-runtime` version is this being run on? I use this code on a daily basis and it should work fine.

2023-04-21 14:36 UTC, pandasa123 commented on notebooks/algorithm-design/cost_function/cost_function.ipynb
@ElePT, it's due to an importing the primitive version in an earlier cell and not importing the runtime estimator in this cell

2023-04-21 15:01 UTC, frankharkins commented on notebooks/algorithm-design/cost_function/cost_function.ipynb
@ElePT I used `0.9.3`

2023-04-21 16:01 UTC, merged