Fixed broken links in Quantum Machine learning course
Qiskit/platypus pull request #795
Opened 2022-03-08 08:01 UTC by divshacker

## Changes
fixes Qiskit-community/qiskit-textbook#1379

## Implementation details
As mentioned in above linked issue, There are 4 points mentioned and I have fixed 2 of them (2nd and 3rd) 

## How to read this PR

## Screenshots

2022-03-08 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/platypus?pullRequest=795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/platypus?pullRequest=795) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/platypus?pullRequest=795) it.</sub>

2022-03-08 08:04 UTC, divshacker commented
For first one I need the correct link and the given link in the issue is not correct.

2022-03-09 17:41 UTC, frankharkins submitted a review, later dismissed
Thank you!

I updated the slack links, and added a `https://` to the quantum lab links.

2022-03-10 09:49 UTC, Tansito requested changes

2022-03-10 09:49 UTC, Tansito commented on notebooks/intro/project.ipynb
> +   "display_name": "Python 3 (ipykernel)",
Thanks for the contribution @divshacker ! Could you remove this change from the PR? We would like to maintain the changes only related with the new links 🙏

2022-03-10 09:49 UTC, Tansito commented on notebooks/intro/project.ipynb
> +   "version": "3.9.10"
Same as my previous comment.

2022-03-10 09:49 UTC, Tansito commented on notebooks/intro/project.ipynb
> +   "version": "3.9.10"
Same as my previous comment.

2022-03-10 09:49 UTC, Tansito commented on notebooks/quantum-machine-learning/kernel.ipynb
> +   "version": "3.8.10"
Same as my previous comment.

2022-03-10 09:49 UTC, Tansito commented on notebooks/quantum-machine-learning/kernel.ipynb
> +   "version": "3.8.10"
Same as my previous comment.

2022-03-10 09:49 UTC, Tansito commented on notebooks/quantum-machine-learning/project.ipynb
> +   "version": "3.9.10"
Same as my previous comment.

2022-03-10 09:49 UTC, Tansito commented on notebooks/quantum-machine-learning/project.ipynb
> +   "version": "3.9.10"
Same as my previous comment.

2022-03-10 09:49 UTC, Tansito commented on notebooks/quantum-machine-learning/training.ipynb
> +   "version": "3.8.10"
And last one change if you can revert it.

2022-03-10 09:49 UTC, Tansito commented on notebooks/quantum-machine-learning/training.ipynb
> +   "version": "3.8.10"
And last one change if you can revert it.

2022-03-10 10:30 UTC, divshacker commented
Hey @Tansito I have fixed all the unnecessary changes. 
Let me know if there is anything else required
Thanks

2022-03-10 10:34 UTC, Tansito approved these changes

2022-03-10 11:18 UTC, merged