Add User profile icon to Textbook navigation
Qiskit/platypus pull request #805
Opened 2022-03-09 19:40 UTC by techtolentino

## Changes
Closes #796 

## Implementation details
- added User icon button link to the nav
- when a user clicks the button, they're taken to their `/account` page
- (if the user isn't logged in, they'll hit the `/signin` page)
- added mobile `Profile` link to mobile-menu

## How to read this PR
- review updates to Textbook menu, + mobile-menu
- review style updates

## Screenshots
https://user-images.githubusercontent.com/6276074/157519554-ecf51561-cee0-4246-a098-c398e523fb3f.mov

2022-03-10 15:11 UTC, techtolentino commented
I didn't consider this earlier, but I'm converting this to draft until the [CourseList bug](https://github.com/Qiskit/platypus/issues/783) is resolved

2022-03-22 18:39 UTC, korgan00 requested changes

2022-03-22 18:39 UTC, korgan00 commented on frontend/vue/components/TheMenu/MobileMenu.vue
> +    AppLink, BasicLink, User16
We use to have one component per line

2022-03-22 18:39 UTC, korgan00 commented on frontend/vue/components/TheMenu/MobileMenu.vue
> +$mobile-menu-item-height: 4rem;
I like this.

2022-03-22 18:39 UTC, korgan00 commented on frontend/vue/components/TheMenu/MobileMenu.vue
> +      border: 1px solid $carbon--purple-70;
I think `$border-color-secondary` is better here

2022-03-22 18:39 UTC, korgan00 commented on frontend/vue/components/TheMenu/MobileMenu.vue
> +      fill: $carbon--purple-70;
Here we should use also a variable defined by us

2022-03-22 18:39 UTC, korgan00 commented on frontend/vue/components/TheMenu/index.vue
> +  components: { AppLink, AppLogo, MobileMenu, BasicLink, Menu20, Close20, User20 }
We use to have one component per line

2022-03-22 18:39 UTC, korgan00 commented on frontend/vue/components/TheMenu/index.vue
> +        background-color: $carbon--purple-80;
We should use the colors in the scss.

2022-03-22 18:40 UTC, korgan00 commented
Good job Randy!
Just few small and quick changes

2022-03-23 12:34 UTC, korgan00 approved these changes
LGTM. Thank you!

2022-03-28 12:50 UTC, eddybrando commented on frontend/vue/components/TheMenu/MobileMenu.vue
>  // import { Component, Mixins, Prop, Watch } from 'vue-property-decorator'
```suggestion
```

2022-03-28 12:52 UTC, eddybrando approved these changes
This is great, @techtolentino! Thank you very much!

2022-03-28 14:32 UTC, merged