worked on issue 881 regarding improving readme for content editors
Qiskit/platypus pull request #961
Opened 2022-04-30 11:16 UTC by gprs1809

## Changes

2022-04-30 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/platypus?pullRequest=961) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/platypus?pullRequest=961) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/platypus?pullRequest=961) it.</sub>

2022-05-03 12:39 UTC, frankharkins requested changes
@gprs1809 thank you! This looks different to [the version](https://github.com/Qiskit/platypus/issues/881#issuecomment-1109575346) you posted in #881, can you update this PR please?

2022-05-03 12:41 UTC, frankharkins approved these changes

2022-05-03 13:09 UTC, vabarbosa approved these changes
thank you @gprs1809

2022-05-03 13:10 UTC, merged